[project]
name = "homedata"
version = "1.0.0"
requires-python = ">=3.13"
dependencies = [
    "duckdb>=1.3.2",
    "paramiko>=3.5.1",
    "pytz>=2025.2",
    "tqdm>=4.67.1",
]

[dependency-groups]
dev = ["black>=25.1.0"]
